/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClassBooking {
  'status' : ClassStatus,
  'bookedAt' : Time,
  'user' : Principal,
  'classId' : string,
}
export type ClassStatus = { 'booked' : null } |
  { 'bookingClosed' : null } |
  { 'waitlisted' : null } |
  { 'fullyBooked' : null };
export type ClassType = { 'mat' : null } |
  { 'refomer' : null } |
  { 'privateSession' : null };
export interface ContactFormSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Instructor {
  'id' : string,
  'bio' : string,
  'name' : string,
  'specialties' : Array<ClassType>,
}
export interface PilatesClass {
  'id' : string,
  'startTime' : Time,
  'status' : ClassStatus,
  'instructor' : string,
  'durationMinutes' : bigint,
  'spotsLeft' : bigint,
  'capacity' : bigint,
  'classType' : ClassType,
}
export interface PrivateSessionRequest {
  'contactMethod' : string,
  'name' : string,
  'submittedAt' : Time,
  'preferredDays' : Array<string>,
  'preferredTime' : string,
  'instructorPreference' : [] | [string],
}
export interface Testimonial {
  'content' : string,
  'author' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserPackage { 'expiresAt' : Time, 'remainingCredits' : bigint }
export interface _SERVICE {
  'addClass' : ActorMethod<[PilatesClass], undefined>,
  'addInstructor' : ActorMethod<[Instructor], undefined>,
  'bookClass' : ActorMethod<[string], ClassStatus>,
  'getAllInstructors' : ActorMethod<[], Array<Instructor>>,
  'getClassSchedule' : ActorMethod<[], Array<PilatesClass>>,
  'getContactForms' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getPrivateSessionRequests' : ActorMethod<[], Array<PrivateSessionRequest>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserBookings' : ActorMethod<[], Array<ClassBooking>>,
  'getUserPackage' : ActorMethod<[Principal], [] | [UserPackage]>,
  'submitContactForm' : ActorMethod<[ContactFormSubmission], undefined>,
  'submitPrivateSessionRequest' : ActorMethod<
    [PrivateSessionRequest],
    undefined
  >,
  'submitTestimonial' : ActorMethod<[Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];