/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ClassStatus = IDL.Variant({
  'booked' : IDL.Null,
  'bookingClosed' : IDL.Null,
  'waitlisted' : IDL.Null,
  'fullyBooked' : IDL.Null,
});
export const ClassType = IDL.Variant({
  'mat' : IDL.Null,
  'refomer' : IDL.Null,
  'privateSession' : IDL.Null,
});
export const PilatesClass = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'status' : ClassStatus,
  'instructor' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'spotsLeft' : IDL.Nat,
  'capacity' : IDL.Nat,
  'classType' : ClassType,
});
export const Instructor = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'specialties' : IDL.Vec(ClassType),
});
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PrivateSessionRequest = IDL.Record({
  'contactMethod' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'preferredDays' : IDL.Vec(IDL.Text),
  'preferredTime' : IDL.Text,
  'instructorPreference' : IDL.Opt(IDL.Text),
});
export const Testimonial = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const ClassBooking = IDL.Record({
  'status' : ClassStatus,
  'bookedAt' : Time,
  'user' : IDL.Principal,
  'classId' : IDL.Text,
});
export const UserPackage = IDL.Record({
  'expiresAt' : Time,
  'remainingCredits' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addClass' : IDL.Func([PilatesClass], [], []),
  'addInstructor' : IDL.Func([Instructor], [], []),
  'bookClass' : IDL.Func([IDL.Text], [ClassStatus], []),
  'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
  'getClassSchedule' : IDL.Func([], [IDL.Vec(PilatesClass)], ['query']),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactFormSubmission)], ['query']),
  'getPrivateSessionRequests' : IDL.Func(
      [],
      [IDL.Vec(PrivateSessionRequest)],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserBookings' : IDL.Func([], [IDL.Vec(ClassBooking)], ['query']),
  'getUserPackage' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserPackage)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
  'submitPrivateSessionRequest' : IDL.Func([PrivateSessionRequest], [], []),
  'submitTestimonial' : IDL.Func([Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ClassStatus = IDL.Variant({
    'booked' : IDL.Null,
    'bookingClosed' : IDL.Null,
    'waitlisted' : IDL.Null,
    'fullyBooked' : IDL.Null,
  });
  const ClassType = IDL.Variant({
    'mat' : IDL.Null,
    'refomer' : IDL.Null,
    'privateSession' : IDL.Null,
  });
  const PilatesClass = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'status' : ClassStatus,
    'instructor' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'spotsLeft' : IDL.Nat,
    'capacity' : IDL.Nat,
    'classType' : ClassType,
  });
  const Instructor = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'specialties' : IDL.Vec(ClassType),
  });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PrivateSessionRequest = IDL.Record({
    'contactMethod' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'preferredDays' : IDL.Vec(IDL.Text),
    'preferredTime' : IDL.Text,
    'instructorPreference' : IDL.Opt(IDL.Text),
  });
  const Testimonial = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const ClassBooking = IDL.Record({
    'status' : ClassStatus,
    'bookedAt' : Time,
    'user' : IDL.Principal,
    'classId' : IDL.Text,
  });
  const UserPackage = IDL.Record({
    'expiresAt' : Time,
    'remainingCredits' : IDL.Nat,
  });
  
  return IDL.Service({
    'addClass' : IDL.Func([PilatesClass], [], []),
    'addInstructor' : IDL.Func([Instructor], [], []),
    'bookClass' : IDL.Func([IDL.Text], [ClassStatus], []),
    'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
    'getClassSchedule' : IDL.Func([], [IDL.Vec(PilatesClass)], ['query']),
    'getContactForms' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getPrivateSessionRequests' : IDL.Func(
        [],
        [IDL.Vec(PrivateSessionRequest)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserBookings' : IDL.Func([], [IDL.Vec(ClassBooking)], ['query']),
    'getUserPackage' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserPackage)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
    'submitPrivateSessionRequest' : IDL.Func([PrivateSessionRequest], [], []),
    'submitTestimonial' : IDL.Func([Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };