/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactFormSubmission {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface Instructor {
    id: string;
    bio: string;
    name: string;
    specialties: Array<ClassType>;
}
export type Time = bigint;
export interface PrivateSessionRequest {
    contactMethod: string;
    name: string;
    submittedAt: Time;
    preferredDays: Array<string>;
    preferredTime: string;
    instructorPreference?: string;
}
export interface PilatesClass {
    id: string;
    startTime: Time;
    status: ClassStatus;
    instructor: string;
    durationMinutes: bigint;
    spotsLeft: bigint;
    capacity: bigint;
    classType: ClassType;
}
export interface ClassBooking {
    status: ClassStatus;
    bookedAt: Time;
    user: Principal;
    classId: string;
}
export interface UserPackage {
    expiresAt: Time;
    remainingCredits: bigint;
}
export interface Testimonial {
    content: string;
    author: string;
    timestamp: Time;
    rating: bigint;
}
export enum ClassStatus {
    booked = "booked",
    bookingClosed = "bookingClosed",
    waitlisted = "waitlisted",
    fullyBooked = "fullyBooked"
}
export enum ClassType {
    mat = "mat",
    refomer = "refomer",
    privateSession = "privateSession"
}
export interface backendInterface {
    addClass(pilatesClass: PilatesClass): Promise<void>;
    addInstructor(instructor: Instructor): Promise<void>;
    bookClass(classId: string): Promise<ClassStatus>;
    getAllInstructors(): Promise<Array<Instructor>>;
    getClassSchedule(): Promise<Array<PilatesClass>>;
    getContactForms(): Promise<Array<ContactFormSubmission>>;
    getPrivateSessionRequests(): Promise<Array<PrivateSessionRequest>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getUserBookings(): Promise<Array<ClassBooking>>;
    getUserPackage(user: Principal): Promise<UserPackage | null>;
    submitContactForm(form: ContactFormSubmission): Promise<void>;
    submitPrivateSessionRequest(request: PrivateSessionRequest): Promise<void>;
    submitTestimonial(testimonial: Testimonial): Promise<void>;
}
import type { ClassBooking as _ClassBooking, ClassStatus as _ClassStatus, ClassType as _ClassType, Instructor as _Instructor, PilatesClass as _PilatesClass, PrivateSessionRequest as _PrivateSessionRequest, Time as _Time, UserPackage as _UserPackage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addClass(arg0: PilatesClass): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClass(to_candid_PilatesClass_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClass(to_candid_PilatesClass_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInstructor(arg0: Instructor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInstructor(to_candid_Instructor_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInstructor(to_candid_Instructor_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bookClass(arg0: string): Promise<ClassStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.bookClass(arg0);
                return from_candid_ClassStatus_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookClass(arg0);
            return from_candid_ClassStatus_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInstructors(): Promise<Array<Instructor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstructors();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstructors();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassSchedule(): Promise<Array<PilatesClass>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassSchedule();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassSchedule();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactForms(): Promise<Array<ContactFormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactForms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactForms();
            return result;
        }
    }
    async getPrivateSessionRequests(): Promise<Array<PrivateSessionRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrivateSessionRequests();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrivateSessionRequests();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getUserBookings(): Promise<Array<ClassBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPackage(arg0: Principal): Promise<UserPackage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPackage(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPackage(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: ContactFormSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async submitPrivateSessionRequest(arg0: PrivateSessionRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPrivateSessionRequest(to_candid_PrivateSessionRequest_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPrivateSessionRequest(to_candid_PrivateSessionRequest_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0);
            return result;
        }
    }
}
function from_candid_ClassBooking_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassBooking): ClassBooking {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ClassStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassStatus): ClassStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ClassType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassType): ClassType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Instructor_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Instructor): Instructor {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PilatesClass_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PilatesClass): PilatesClass {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PrivateSessionRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrivateSessionRequest): PrivateSessionRequest {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPackage]): UserPackage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    name: string;
    specialties: Array<_ClassType>;
}): {
    id: string;
    bio: string;
    name: string;
    specialties: Array<ClassType>;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        specialties: from_candid_vec_n15(_uploadFile, _downloadFile, value.specialties)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: _Time;
    status: _ClassStatus;
    instructor: string;
    durationMinutes: bigint;
    spotsLeft: bigint;
    capacity: bigint;
    classType: _ClassType;
}): {
    id: string;
    startTime: Time;
    status: ClassStatus;
    instructor: string;
    durationMinutes: bigint;
    spotsLeft: bigint;
    capacity: bigint;
    classType: ClassType;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_ClassStatus_n10(_uploadFile, _downloadFile, value.status),
        instructor: value.instructor,
        durationMinutes: value.durationMinutes,
        spotsLeft: value.spotsLeft,
        capacity: value.capacity,
        classType: from_candid_ClassType_n16(_uploadFile, _downloadFile, value.classType)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactMethod: string;
    name: string;
    submittedAt: _Time;
    preferredDays: Array<string>;
    preferredTime: string;
    instructorPreference: [] | [string];
}): {
    contactMethod: string;
    name: string;
    submittedAt: Time;
    preferredDays: Array<string>;
    preferredTime: string;
    instructorPreference?: string;
} {
    return {
        contactMethod: value.contactMethod,
        name: value.name,
        submittedAt: value.submittedAt,
        preferredDays: value.preferredDays,
        preferredTime: value.preferredTime,
        instructorPreference: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.instructorPreference))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ClassStatus;
    bookedAt: _Time;
    user: Principal;
    classId: string;
}): {
    status: ClassStatus;
    bookedAt: Time;
    user: Principal;
    classId: string;
} {
    return {
        status: from_candid_ClassStatus_n10(_uploadFile, _downloadFile, value.status),
        bookedAt: value.bookedAt,
        user: value.user,
        classId: value.classId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    booked: null;
} | {
    bookingClosed: null;
} | {
    waitlisted: null;
} | {
    fullyBooked: null;
}): ClassStatus {
    return "booked" in value ? ClassStatus.booked : "bookingClosed" in value ? ClassStatus.bookingClosed : "waitlisted" in value ? ClassStatus.waitlisted : "fullyBooked" in value ? ClassStatus.fullyBooked : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mat: null;
} | {
    refomer: null;
} | {
    privateSession: null;
}): ClassType {
    return "mat" in value ? ClassType.mat : "refomer" in value ? ClassType.refomer : "privateSession" in value ? ClassType.privateSession : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Instructor>): Array<Instructor> {
    return value.map((x)=>from_candid_Instructor_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassType>): Array<ClassType> {
    return value.map((x)=>from_candid_ClassType_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PilatesClass>): Array<PilatesClass> {
    return value.map((x)=>from_candid_PilatesClass_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrivateSessionRequest>): Array<PrivateSessionRequest> {
    return value.map((x)=>from_candid_PrivateSessionRequest_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassBooking>): Array<ClassBooking> {
    return value.map((x)=>from_candid_ClassBooking_n26(_uploadFile, _downloadFile, x));
}
function to_candid_ClassStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassStatus): _ClassStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ClassType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassType): _ClassType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Instructor_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Instructor): _Instructor {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PilatesClass_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PilatesClass): _PilatesClass {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PrivateSessionRequest_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrivateSessionRequest): _PrivateSessionRequest {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: Time;
    status: ClassStatus;
    instructor: string;
    durationMinutes: bigint;
    spotsLeft: bigint;
    capacity: bigint;
    classType: ClassType;
}): {
    id: string;
    startTime: _Time;
    status: _ClassStatus;
    instructor: string;
    durationMinutes: bigint;
    spotsLeft: bigint;
    capacity: bigint;
    classType: _ClassType;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: to_candid_ClassStatus_n3(_uploadFile, _downloadFile, value.status),
        instructor: value.instructor,
        durationMinutes: value.durationMinutes,
        spotsLeft: value.spotsLeft,
        capacity: value.capacity,
        classType: to_candid_ClassType_n5(_uploadFile, _downloadFile, value.classType)
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactMethod: string;
    name: string;
    submittedAt: Time;
    preferredDays: Array<string>;
    preferredTime: string;
    instructorPreference?: string;
}): {
    contactMethod: string;
    name: string;
    submittedAt: _Time;
    preferredDays: Array<string>;
    preferredTime: string;
    instructorPreference: [] | [string];
} {
    return {
        contactMethod: value.contactMethod,
        name: value.name,
        submittedAt: value.submittedAt,
        preferredDays: value.preferredDays,
        preferredTime: value.preferredTime,
        instructorPreference: value.instructorPreference ? candid_some(value.instructorPreference) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    name: string;
    specialties: Array<ClassType>;
}): {
    id: string;
    bio: string;
    name: string;
    specialties: Array<_ClassType>;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        specialties: to_candid_vec_n9(_uploadFile, _downloadFile, value.specialties)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassStatus): {
    booked: null;
} | {
    bookingClosed: null;
} | {
    waitlisted: null;
} | {
    fullyBooked: null;
} {
    return value == ClassStatus.booked ? {
        booked: null
    } : value == ClassStatus.bookingClosed ? {
        bookingClosed: null
    } : value == ClassStatus.waitlisted ? {
        waitlisted: null
    } : value == ClassStatus.fullyBooked ? {
        fullyBooked: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassType): {
    mat: null;
} | {
    refomer: null;
} | {
    privateSession: null;
} {
    return value == ClassType.mat ? {
        mat: null
    } : value == ClassType.refomer ? {
        refomer: null
    } : value == ClassType.privateSession ? {
        privateSession: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ClassType>): Array<_ClassType> {
    return value.map((x)=>to_candid_ClassType_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
